In [1]:
#NUMPY BASICS
import numpy as np

In [2]:
A = np.arange(3*2).reshape(3,2)

#broadcasting
B = 10 * np.arange(3*2).reshape(3,2)

X = np.arange(3*2)
print("X:\n",X)
print("A:\n",A)
print("B:\n",B)

X:
 [0 1 2 3 4 5]
A:
 [[0 1]
 [2 3]
 [4 5]]
B:
 [[ 0 10]
 [20 30]
 [40 50]]


In [3]:
#ADDITION: 

In [4]:
A + B

array([[ 0, 11],
       [22, 33],
       [44, 55]])

In [5]:
#if we have different dimensions -> broadcasting happens

#we can add scalars to the whole array
A + 100 

array([[100, 101],
       [102, 103],
       [104, 105]])

In [6]:
temp = 100*np.arange(2).reshape(2)
print("Temp:\n",temp)
print(temp.shape)
print("A:\n",A)
print(A.shape)

Temp:
 [  0 100]
(2,)
A:
 [[0 1]
 [2 3]
 [4 5]]
(3, 2)


In [7]:
#Broadcasting
A + temp

array([[  0, 101],
       [  2, 103],
       [  4, 105]])

In [8]:
temp = 100*np.arange(3*2).reshape(2,3)
print("Temp:\n",temp)
print(temp.shape)
print("A:\n",A)
print(A.shape)

Temp:
 [[  0 100 200]
 [300 400 500]]
(2, 3)
A:
 [[0 1]
 [2 3]
 [4 5]]
(3, 2)


In [9]:
#Numpy only broadcasts in one direction 
A + temp

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [10]:
#Dot Product 

A = np.arange(3*2).reshape(3,2)

#broadcasting
B = 10 * np.arange(3*2).reshape(3,2)

X = np.arange(3*2)
print("X:\n",X)
print("A:\n",A)
print("B:\n",B)

X:
 [0 1 2 3 4 5]
A:
 [[0 1]
 [2 3]
 [4 5]]
B:
 [[ 0 10]
 [20 30]
 [40 50]]


In [11]:
A * B

array([[  0,  10],
       [ 40,  90],
       [160, 250]])

In [12]:
mul = 100*np.arange(2).reshape(2) 
print("mul:\n",mul)
print(mul.shape)
print("A:\n",A) 
A * mul

mul:
 [  0 100]
(2,)
A:
 [[0 1]
 [2 3]
 [4 5]]


array([[  0, 100],
       [  0, 300],
       [  0, 500]])

In [13]:
mul = 100*np.arange(3*2).reshape(3,2) 
print("mul:\n",mul)
print(mul.shape)
print("A:\n",A) 
A * mul

mul:
 [[  0 100]
 [200 300]
 [400 500]]
(3, 2)
A:
 [[0 1]
 [2 3]
 [4 5]]


array([[   0,  100],
       [ 400,  900],
       [1600, 2500]])

In [14]:
#broadcasting doesn't work
mul = 100*np.arange(3*2).reshape(2,3) 
print("mul:\n",mul)
print(mul.shape)
print("A:\n",A) 
A * mul

mul:
 [[  0 100 200]
 [300 400 500]]
(2, 3)
A:
 [[0 1]
 [2 3]
 [4 5]]


ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [15]:
#A.T -> to transpose

In [16]:
np.dot(A,B.T)

array([[ 10,  30,  50],
       [ 30, 130, 230],
       [ 50, 230, 410]])

In [17]:
A.dot(B.T)

array([[ 10,  30,  50],
       [ 30, 130, 230],
       [ 50, 230, 410]])

In [18]:
A @ B.T

array([[ 10,  30,  50],
       [ 30, 130, 230],
       [ 50, 230, 410]])

In [19]:
np.matmul(A,B.T)

array([[ 10,  30,  50],
       [ 30, 130, 230],
       [ 50, 230, 410]])

In [20]:
print(A[:,1])
print(B[:,1])

[1 3 5]
[10 30 50]


In [21]:
np.cross(A[:,1],B[:,1])

array([0, 0, 0])

In [22]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# performing matrix multiplication using .dot and storing the result in result_dot
result_dot = np.dot(a, b)

# performing matrix multiplication using .matmul and storing the result in result_matmul
result_matmul = np.matmul(a, b)

# performing matrix multiplication using the @ operator and storing the result in result_at
result_at = a @ b

# displaying the results of matrix multiplication
print("Result using .dot:", result_dot)
print("Result using .matmul:", result_matmul)
print("Result using @:", result_at)

# initializing random 3D arrays c and d
c = np.random.rand(2, 2, 2)
d = np.random.rand(2, 2, 2)

# performing matrix multiplication using .dot on 3D arrays and storing the result in result_dot_higher
result_dot_higher = np.dot(c, d)

# performing matrix multiplication using .matmul on 3D arrays and storing the result in result_matmul_higher
result_matmul_higher = np.matmul(c, d)

# displaying the results of matrix multiplication on higher dimensional arrays
print("Result of higher dim using .dot:\n", result_dot_higher)
print("\nResult of higher dim using .matmul:", result_matmul_higher)


Result using .dot: [[19 22]
 [43 50]]
Result using .matmul: [[19 22]
 [43 50]]
Result using @: [[19 22]
 [43 50]]
Result of higher dim using .dot:
 [[[[0.25042496 0.1335071 ]
   [0.19562969 0.42193583]]

  [[0.67644466 0.29077666]
   [0.06090049 0.67748125]]]


 [[[0.41014415 0.22647595]
   [0.37273568 0.74278656]]

  [[0.32291427 0.18045561]
   [0.30783099 0.59901662]]]]

Result of higher dim using .matmul: [[[0.25042496 0.1335071 ]
  [0.67644466 0.29077666]]

 [[0.37273568 0.74278656]
  [0.30783099 0.59901662]]]


In [23]:
'''
# Comparing `.dot` and `.matmul` in NumPy for Higher-dimensional Arrays

In NumPy, both `.dot` and `.matmul` are used for matrix multiplication. 
While they behave similarly for 2D arrays, there are key differences when higher-dimensional 
arrays are involved.

## `.dot` Method

The `.dot` function performs matrix multiplication that can handle multi-dimensional arrays.
For 2D matrices, it behaves as standard matrix multiplication.

### What is a Stack of Matrices?

A 3D array like 

```python
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
can be considered a stack of three 2D matrices:

[[1, 2], [3, 4]]
[[5, 6], [7, 8]]
[[9, 10], [11, 12]]
In the case of .dot, these slices would be combined with corresponding slices from the 
other array involved in the operation.

Example Code for .dot:

import numpy as np
c = np.random.rand(2, 2, 2)
d = np.random.rand(2, 2, 2)
result_dot_higher = np.dot(c, d)


.matmul Method
.matmul performs matrix multiplication that's more specialized for 2D matrices. 
For higher-dimensional arrays, .matmul performs "batch" matrix multiplication over the 
last two dimensions.

Example Code for .matmul:

result_matmul_higher = np.matmul(c, d)

'''

'\n# Comparing `.dot` and `.matmul` in NumPy for Higher-dimensional Arrays\n\nIn NumPy, both `.dot` and `.matmul` are used for matrix multiplication. \nWhile they behave similarly for 2D arrays, there are key differences when higher-dimensional \narrays are involved.\n\n## `.dot` Method\n\nThe `.dot` function performs matrix multiplication that can handle multi-dimensional arrays.\nFor 2D matrices, it behaves as standard matrix multiplication.\n\n### What is a Stack of Matrices?\n\nA 3D array like \n\n```python\narray_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])\ncan be considered a stack of three 2D matrices:\n\n[[1, 2], [3, 4]]\n[[5, 6], [7, 8]]\n[[9, 10], [11, 12]]\nIn the case of .dot, these slices would be combined with corresponding slices from the \nother array involved in the operation.\n\nExample Code for .dot:\n\nimport numpy as np\nc = np.random.rand(2, 2, 2)\nd = np.random.rand(2, 2, 2)\nresult_dot_higher = np.dot(c, d)\n\n\n.matmul Method\n.matm

In [24]:
# creating a 2x3 array filled with zeros
a = np.zeros((2, 3))

# creating a 1D array with shape (3,)
b = np.array([1, 2, 3])

# adding 'a' and 'b' together using broadcasting
# broadcasting stretches 'b' to have the same shape as 'a' 
# so that they can be added together
result = a + b

print("Array 'a':\n", a)
print("Array 'b':\n", b)
print("Result of broadcasting and addition:\n", result)


Array 'a':
 [[0. 0. 0.]
 [0. 0. 0.]]
Array 'b':
 [1 2 3]
Result of broadcasting and addition:
 [[1. 2. 3.]
 [1. 2. 3.]]


In [25]:
# creating a 2x3 array
a = np.array([[1, 2, 3], [4, 5, 6]])

# creating another 2x3 array but transposed to 3x2
b = np.array([[1, 4], [2, 5], [3, 6]])

try:
    # trying to add 'a' and 'b' together
    # since the shapes don't align properly, broadcasting is not happening
    # this will throw a ValueError
    result = a + b
except ValueError as e:
    print(f"An error occurred: {e}")
    print("Broadcasting did not happen because dimensions are not aligned.")

# creating a 1D array with shape (4,)
c = np.array([1, 2, 3, 4])

try:
    # trying to add 'a' and 'c' together
    # shapes are not compatible for broadcasting
    # this is dangerous as it will throw a ValueError
    dangerous_result = a + c
except ValueError as e:
    print(f"An error occurred: {e}")
    print("This is dangerous because the dimensions are not even close.")


An error occurred: operands could not be broadcast together with shapes (2,3) (3,2) 
Broadcasting did not happen because dimensions are not aligned.
An error occurred: operands could not be broadcast together with shapes (2,3) (4,) 
This is dangerous because the dimensions are not even close.
